### PR TITLE
Add neuralprophet 0.3.2

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Bug Tracker: https://github.com/ourownstory/neural_prophet/issues
Releases: https://github.com/ourownstory/neural_prophet/releases
License: https://github.com/ourownstory/neural_prophet/blob/main/LICENSE
Requirements: 
- https://github.com/ourownstory/neural_prophet/blob/0.3.2/requirements.txt
- https://github.com/ourownstory/neural_prophet/blob/0.3.2/setup.py

Actions:
1. Skip `py<36`
2. Skip `win32` and `s390x` (`lunarcalendar `dependencies currently aren't available on s390x)
3. Skip `py==310 and (linux and ppc64le)`: Unsatisfiable dependencies for platform linux-ppc64le with python 3.10
4. Add my `fix_scripts.patch` to fix an incorrect name of the file `neuralprophet_dev_setup` in the `scripts` folder https://github.com/ourownstory/neural_prophet/tree/0.3.2/scripts and in the `setup.py`
5. Fix dataclasses in run: `dataclasses >=0.6  # [py<37]`, see https://github.com/ourownstory/neural_prophet/commit/ceabfca7a11b9501e318b78b032251601268eaeb
6. Disable `pip check`: `neuralprophet 0.3.2 requires a package dataclasses, which is not installed` but `dataclasses 0.8` is available in the test environment. The mainstream source will fix it in the next version 0.3.3.
7. Add `tests/` into `source_files` and the `pytest` command from https://github.com/ourownstory/neural_prophet/blob/fd64ac48ba461b78e8b39d8a738f6d6632546ef7/.github/workflows/ci.yml#L29

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
It's not clear what's dependent package causes an issue with python 3.10 on ppc64le.
After running the command:
`CONDA_SUBDIR=linux-ppc64le conda create -n test_env --dry-run python=3.10 patch pip setuptools wheel "convertdate >=2.1.2" "dataclasses >=0.6" "holidays >=0.11.3.1" "ipywidgets >=7.5.1" "lunarcalendar >=0.0.9" "matplotlib-base >=2.0.0" "numpy >=1.15.4" "pandas >=1.0.4" "python-dateutil >=2.8.0" "pytorch >=1.4.0" "torch-lr-finder >=0.2.1" "tqdm >=4.50.2" -vvv 2>&1 | grep -e "-> 0"`
there is no errors

**Review by varlackc — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
Skip tests for python 3.7, 3.10. The main issue is incompatibility with `pytorch`.
And skip on ppc64le where is an issue with AVX.

**Comment by tobijk** [comment]
Hm, do you have more information on the compatibility issue with pytorch?

**Review by tobijk — APPROVED** [review]
LGTM 👍

**Comment by skupr-anaconda** [comment]
> Hm, do you have more information on the compatibility issue with pytorch?

I reported the upstream source about issues with python 3.7 https://github.com/ourownstory/neural_prophet/issues/615
But neuralprophet 0.3.2 has another issue with python 3.10 and pytorch. It seems like neuralprophet tests don't feel good with python 3.10

**Review by katietz — APPROVED** [review]
Do you have details on the packages missing on ppc64le?
otherwise looks good, thanks!

**Comment by skupr-anaconda** [comment]
> Do you have details on the packages missing on ppc64le? otherwise looks good, thanks!

No, I didn't find the missing package. I'll create a JIRA ticket for ppc64le with python 3.10

**Pull request merged**
